export const RECIPE_RESULTS_REQUEST = 'RECIPE_RESULTS_REQUEST';
export const RECIPE_RESULTS_SUCCESS = 'RECIPE_RESULTS_SUCCESS';
export const RECIPE_RESULTS_FAILURE = 'RECIPE_RESULTS_FAILURE';

export const RECIPE_PAGE_CHANGE_REQUEST = 'RECIPE_PAGE_CHANGE_REQUEST';
export const RECIPE_PAGE_CHANGE_SUCCESS = 'RECIPE_PAGE_CHANGE_SUCCESS';

export const RECIPE_CARD_REQUEST = 'RECIPE_CARD_REQUEST';
export const RECIPE_CARD_SUCCESS = 'RECIPE_CARD_SUCCESS';
export const RECIPE_CARD_FAILURE = 'RECIPE_CARD_FAILURE';

export const RECIPE_NUTRITION_REQUEST = 'RECIPE_NUTRITION_REQUEST';
export const RECIPE_NUTRITION_SUCCESS = 'RECIPE_NUTRITION_SUCCESS';
export const RECIPE_NUTRITION_FAILURE = 'RECIPE_NUTRITION_FAILURE';

export const RECIPE_TASTE_REQUEST = 'RECIPE_TASTE_REQUEST';
export const RECIPE_TASTE_SUCCESS = 'RECIPE_TASTE_SUCCESS';
export const RECIPE_TASTE_FAILURE = 'RECIPE_TASTE_FAILURE';

export const SIMILAR_RECIPE_REQUEST = 'SIMILAR_RECIPE_REQUEST';
export const SIMILAR_RECIPE_SUCCESS = 'SIMILAR_RECIPE_SUCCESS';
export const SIMILAR_RECIPE_FAILURE = 'SIMILAR_RECIPE_FAILURE';

export const SET_NUTRITION_FILTERS = 'SET_NUTRITION_FILTERS';

export const RESULTS = 'RESULTS';
export const PAGE = 'PAGE';
export const NUTRITION_FILTERS = 'NUTRITION_FILTERS';
