export const USER_REQUEST_ATTEMPT = 'USER_REQUEST_ATTEMPT';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAILURE = 'USER_REQUEST_FAILURE';

export const SHOW_INGREDIENT_TOOL = 'SHOW_INGREDIENT_TOOL';
export const HIDE_INGREDIENT_TOOL = 'HIDE_INGREDIENT_TOOL';

export const DATA = 'DATA';
export const LOGGED_IN = 'LOGGED_IN';
